-- {"id":412381,"ver":"0.1.0","libVer":"1.0.0","author":"N4O","dep":["Madara>=2.9.0"]}

return Require("Madara")("https://www.novelmultiverse.com", {
    id = 412381,
    name = "Novel Multiverse",
    imageURL = "https://github.com/noaione/shosetsu-extensions/raw/dev/icons/NovelMultiverse.png",

    -- defaults values
    latestNovelSel = "div.page-listing-item",
    ajaxUsesFormData = true,

    -- There are paid chapters, we can ignore it
    chaptersListSelector= "li.wp-manga-chapter.free-chap",

    genres = {
        "Action",
        "Adult",
        "Adventure",
        "Anime",
        "Cartoon",
        "Comedy",
        "Comic",
        "Cooking",
        "Detective",
        "Doujinshi",
        "Drama",
        "Ecchi",
        "Fantasy",
        "Gender Bender",
        "Harem",
        "Historical",
        "Horror",
        "Josei",
        "Live action",
        "Manga",
        "Manhua",
        "Manhwa",
        "Martial Arts",
        "Mature",
        "Mecha",
        "Mystery",
        "One shot",
        "Original",
        "Psychological",
        "Romance",
        "School Life",
        "Sci-fi",
        "Seinen",
        "Shoujo",
        "Shoujo Ai",
        "Shounen",
        "Shounen Ai",
        "Slice of Life",
        "Smut",
        "Soft Yaoi",
        "Soft Yuri",
        "Sports",
        "Supernatural",
        "Tragedy",
        "Translation",
        "Webtoon",
        "Wuxia",
        "Xianxia",
        "Xuanhuan",
        "Yaoi",
        "Yuri",
    }
})
